apiVersion: v1
kind: Secret
metadata:
  name: prodia-secrets
  namespace: prodia
type: Opaque
data:
  DB_PASSWORD: RGV2ZWxvcG1lbnQxMjM=
  JWT_SECRET: ZGV2ZWxvcG1lbnRqd3Q=
  POSTGRES_PASSWORD: RGV2ZWxvcG1lbnQxMjM=
