apiVersion: v1
kind: ConfigMap
metadata:
  name: prodia-config
  namespace: prodia
data:
  DB_HOST: "prodia-postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "prodia_db"
  DB_USER: "prodia_user"
  BACKEND_PORT: "5001"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "7d"
  CORS_ORIGIN: "http://182.23.45.203:30091"
  FRONTEND_PORT: "5000"
  BACKEND_URL: "http://prodia-backend-svc:5001"
  API_BASE: "http://182.23.45.203:30091/api"
