apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodia-backend
  namespace: prodia
  labels:
    app: prodia-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prodia-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: prodia-backend
    spec:
      containers:
        - name: backend
          image: ilyasjaelani/prodia-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: BACKEND_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prodia-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: prodia-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: JWT_EXPIRES_IN
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: prodia-config
                  key: CORS_ORIGIN
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: prodia-backend-svc
  namespace: prodia
spec:
  selector:
    app: prodia-backend
  ports:
    - port: 5001
      targetPort: 5001
